backend:
  replicaCount: 1
  image:
    repository: ghcr.io/victorpetrosyan/devops_project/backend
    tag: 444ecf503275d13d4fe6fd719ba0b15cfbba3ee4
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5000
  env:
    PORT: 5000
    DB_PORT: 5432
frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/victorpetrosyan/devops_project/frontend
    tag: 444ecf503275d13d4fe6fd719ba0b15cfbba3ee4
  service:
    type: NodePort
    port: 80
    nodePort: 30000
postgresql:
  auth:
    database: shopdb
    username: postgres
    password: postgres123
  primary:
    persistence:
      enabled: true
      storageClass: local-path
      size: 1Gi
