apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: postgres
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: "18.6.2"

      helm:
        valueFiles:
            - $values/database/values.yaml
 
    - repoURL: https://github.com/victorpetrosyan/devops_project.git
      targetRevision: main
      ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: database

  syncPolicy:
    automated:
      prune: true
      selfHeal: true