name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ── Checkout code ──────────────────────────────────────────────────────
      - name: Checkout code
        uses: actions/checkout@v4

      # ── Login to ghcr.io ───────────────────────────────────────────────────
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u victorpetrosyan --password-stdin

      # ── Build and push backend ─────────────────────────────────────────────
      - name: Build and push backend
        run: |
          docker build -t ghcr.io/victorpetrosyan/devops-shop-backend:latest ./backend
          docker push ghcr.io/victorpetrosyan/devops-shop-backend:latest

      # ── Build and push frontend ────────────────────────────────────────────
      - name: Build and push frontend
        run: |
          docker build -t ghcr.io/victorpetrosyan/devops-shop-frontend:latest ./frontend
          docker push ghcr.io/victorpetrosyan/devops-shop-frontend:latest

      # ── Deploy to Kubernetes ───────────────────────────────────────────────
     # - name: Deploy to Kubernetes
     #   uses: appleboy/ssh-action@v1.0.3
      #  with:
       #   host: ${{ secrets.SSH_HOST }}
        #  username: ${{ secrets.SSH_USER }}
         # key: ${{ secrets.SSH_PRIVATE_KEY }}
         # script: |
          #  kubectl rollout restart deployment/backend -n shop
          #  kubectl rollout restart deployment/frontend -n shop
          #  kubectl rollout status deployment/backend -n shop
          #  kubectl rollout status deployment/frontend -n shop
