name: CI-CD

permissions:
  contents: read
  packages: write

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE: ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
  FRONTEND_IMAGE: ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
  KUBE_NAMESPACE: shop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔐 Login to GHCR
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 🐳 Build backend
      - name: Build backend image
        run: docker build -t $BACKEND_IMAGE ./backend

      - name: Push backend image
        run: docker push $BACKEND_IMAGE

      # 🐳 Build frontend
      - name: Build frontend image
        run: docker build -t $FRONTEND_IMAGE ./frontend

      - name: Push frontend image
        run: docker push $FRONTEND_IMAGE


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      # ☸️ kubeconfig
      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > $HOME/.kube/config

      # 🚀 Deploy backend + frontend
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/backend backend=$BACKEND_IMAGE -n $KUBE_NAMESPACE
          kubectl set image deployment/frontend frontend=$FRONTEND_IMAGE -n $KUBE_NAMESPACE

          kubectl rollout status deployment/backend -n $KUBE_NAMESPACE
          kubectl rollout status deployment/frontend -n $KUBE_NAMESPACE
