name: CI-CD

permissions:
  contents: read
  packages: write

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE: ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
  FRONTEND_IMAGE: ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
  KUBE_NAMESPACE: shop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build backend image
        run: docker build -t $BACKEND_IMAGE ./backend

      - name: Push backend image
        run: docker push $BACKEND_IMAGE

      - name: Build frontend image
        run: docker build -t $FRONTEND_IMAGE ./frontend

      - name: Push frontend image
        run: docker push $FRONTEND_IMAGE


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup kubectl
        uses: azure/setup-helm@v4

      - name: Deploy
        run: |
          helm upgrade --install shop ./devops_chart/ \
          --set backend.image.tag=$BACKEND_IMAGE \
          --set backend.image.tag=$FRONTEND_IMAGE -n $KUBE_NAMESPACE

